server {
    domains: localhost, "{beta,local,}.lstv.{space, localhost}", "{do1l878my2ui3,d1yn3usvpqkzy5}.{cloudfront.net, lstv.space}";
    canonical: "lstv.space";
    root: /static;

    redirect_https;
    redirect_www;
}

addon("~/backend");

route (
    "/robots.txt",
    "/sitemap.xml",
    "/assets/**",
    "/apps/**"
) to: "~/$url";

location (/favicon.ico) alias: "~/assets/image/favicon.svg";
# location ("/home/{account, profile, apps, dev, sub-users, bots, keys, api, support}") alias: "/home/index.html";

location ("/home/!{index.html, index.css, index.js}") alias: "/home/index.html";
location ("/home/applications/{*,*/details,*/store,*/team,*/delete}") alias: "/home/index.html";

location ("/post/!{index.html, index.css, index.js}") alias: "/post/index.html";
location ("/chat/{,user/*,community/*,community/*/*}") alias: "/chat/index.html";

location ("/sign-up") alias: "/login"; # They are the same page
location ("/{pp, privacy}") alias: "/privacy-policy";
location ("/{terms, terms-of-service}") alias: "/tos";

location ("/~/backend/**") deny;

errors 404: /errors/404.html;

# Redirect for Discord
redirect(/discord) to: "https://discord.gg/jQm9yGKCEC";

# Check-in endpoint for analytics/session pings + server events
handle (/check-in) {
    as: "api.extragon.cloud";
    path: /v1/session;
}

ratelimit limit: 5000;

constants {
    kernel-version: "1.2.3-beta";
}

scss { enabled }

postcss {
    enabled;
    extensions: autoprefixer;

    # Scopes CSS files to their folder, that is to avoid conflicts when multiple unsandboxed pages are visible in the same root.
    # Inside you can use :root to refer to the page.
    scoped: to-file;
    scope-exclude: "assets";
}

esbuild {
    targets: "chrome108", "firefox102", "safari16";
}

# Minimum browser version required
browserSupport {
    chrome: 108;
    firefox: 102;
}